import ContactUs from './ContactUs';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
	title: 'Purple Line Plastics | Contact us',
	description: 'Generated by create next app',
};
export default function page() {
	return (
		<main>
			<ContactUs />
		</main>
	);
}
