import { routes } from './routes';

type NavItems = {
	text: string;
	link: string;
}[];

type PageProperties = {
	type: string;
	productCode: string;
	colour: string;
}[];

type Description = {
	closure: string;
	pet: string;
	clear: string;
	dimensions: string;
	mixture: string;
}[];

export type BestSellers = {
	image: string;
	product: string;
	description: Description;
	productType: string;
	viewProduct: string;
	enquire: string;
	pageProperties: PageProperties;
}[];

export const navItems: NavItems = [
	{
		text: 'Bottles',
		link: routes.bottles,
	},
	{
		text: 'Closure',
		link: '#',
	},
	{
		text: 'Jars',
		link: '#',
	},
	{
		text: 'Tablet Containers',
		link: '#',
	},
	{
		text: 'Buoyancy',
		link: '#',
	},
	{
		text: 'Top Sellers',
		link: routes.topSellers,
	},
	{
		text: 'Social',
		link: '#',
	},
	{
		text: 'Contact us',
		link: routes.contactUs,
	},
];

export const footerNavItems: NavItems = [
	{
		text: 'Bottles',
		link: '#',
	},
	{
		text: 'Closures',
		link: '#',
	},
	{
		text: 'Jars',
		link: '#',
	},
	{
		text: 'Tablet Containers',
		link: '#',
	},
	{
		text: 'Buoyancy',
		link: '#',
	},
	{
		text: 'Custom',
		link: '#',
	},
];

export const products = [
	//bell
	{
		id: 0,
		title: 'Bell 500ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '151 x Ø76',
		mixture: '490 minimum',
		images: [
			'/products/bell/bell-500ml.png',
			'/products/bell/bell-500ml-2.png',
		],
		type: 'bell',
	},
	//Boston
	{
		id: 1,
		title: 'Boston 30ml',
		closure: '18/415 closure',
		pet: 'PET',
		clear: 'Clear / White',
		mixture: '1500 minimum',
		images: [
			'/products/boston/boston-30ml.png',
			'/products/boston/boston-30ml-2.png',
		],
		type: 'boston',
	},
	{
		id: 2,
		title: 'Boston 250ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear / White',
		dimensions: '128 x Ø 58',
		mixture: '420 minimum',
		images: ['/products/boston/boston-250ml.png'],
		type: 'boston',
	},
	{
		id: 3,
		title: 'Boston 300ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear / White',
		dimensions: '150 x Ø 58',
		mixture: '324 minimum',
		images: ['/products/boston/boston-300ml.png'],
		type: 'boston',
	},
	{
		id: 4,
		title: 'Boston 500ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear / White',
		dimensions: '175 x Ø 68',
		mixture: '420 minimum',
		images: ['/products/boston/boston-500ml.png'],
		type: 'boston',
	},
	//bullet
	{
		id: 5,
		title: 'Bullet 50ml',
		closure: '24/410 closure',
		pet: 'HDPE',
		clear: 'Wht / Nat/ Blck',
		dimensions: '79 x Ø 35',
		mixture: '1680 minimum',
		images: [
			'/products/bullet/bullet-50ml.png',
			'/products/bullet/bullet-50ml-2.png',
		],
		type: 'bullet',
	},
	{
		id: 6,
		title: 'Bullet 250ml',
		closure: '24/410 closure',
		pet: 'HDPE',
		clear: 'Wht / Nat/ Blck',
		dimensions: '175 x Ø50',
		mixture: '420 minimum',
		images: [
			'/products/bullet/bullet-250ml.png',
			'/products/bullet/bullet-250ml-2.png',
			'/products/bullet/bullet-250ml-black.png',
			'/products/bullet/bullet-250ml-black-2.png',
		],
		type: 'bullet',
	},
	{
		id: 7,
		title: 'Bullet 750ml',
		closure: '28/410 closure',
		pet: 'HDPE',
		clear: 'Natural',
		dimensions: '214 x Ø70',
		mixture: '324 minimum',
		images: [
			'/products/bullet/bullet-750ml.png',
			'/products/bullet/bullet-750ml-2.png',
		],
		type: 'bullet',
	},
	{
		id: 8,
		title: 'Bullet 500ml',
		closure: '28/410 closure',
		pet: 'HDPE',
		clear: 'Wht / Nat',
		dimensions: '197 x Ø65',
		mixture: '400 minimum',
		images: [
			'/products/bullet/bullet-500ml.png',
			'/products/bullet/bullet-500ml-2.png',
			'/products/bullet/bullet-500ml-3.png',
		],
		type: 'bullet',
	},
	{
		id: 9,
		title: 'Buoyancy',
		closure: 'Sealed',
		pet: 'HDPE',
		clear: 'Black',
		dimensions: '224 height / 6 Sided',
		mixture: '1000ml volume / 162 minimum',
		images: [
			'/products/buoyancy/buoyancy.png',
			'/products/buoyancy/buoyancy-2.png',
		],
		type: 'buoyancy',
	},
	//closures-b
	{
		id: 10,
		title: 'Oval Flip',
		closure: 'Custom',
		pet: 'PP',
		clear: 'Various Colors',
		mixture: '1700 minimum	',
		images: [
			'/products/closures-b/oval-flip.png',
			'/products/closures-b/oval-flip-2.png',
			'/products/closures-b/oval-flip-pink.png',
			'/products/closures-b/oval-flip-pink-2.png',
		],
		type: 'closures-b',
	},
	{
		id: 11,
		title: 'Metal',
		closure: '20, 24 & 28',
		pet: 'Metal',
		clear: 'Silver/White/Black/Gold',
		mixture: '420 minimum',
		images: ['/products/closures-b/metal.png'],
		type: 'closures-b',
	},
	{
		id: 12,
		title: 'Big Flip',
		closure: '24 / 410',
		pet: 'PP',
		clear: 'Natural',
		mixture: '420 minimum',
		images: [
			'/products/closures-b/big-flip.png',
			'/products/closures-b/big-flip-2.png',
		],
		type: 'closures-b',
	},
	{
		id: 13,
		title: 'Overcap',
		closure: 'Various Sizes',
		pet: 'PP',
		clear: 'Natural / Black',
		mixture: '420 / 1200 minimum',
		images: ['/products/closures-b/overcap.png'],
		type: 'closures-b',
	},
	{
		id: 14,
		title: 'Flute',
		closure: '24 / 410',
		pet: 'PP',
		clear: 'Natural / Black',
		mixture: '420 minimum',
		images: ['/products/closures-b/flute.png'],
		type: 'closures-b',
	},
	//hosp-30s
	{
		id: 15,
		title: '30 Tottle',
		closure: 'Clip-on',
		pet: 'PP',
		clear: 'Natural',
		dimensions: '73 x Ø36 x Ø24',
		mixture: '2600 minimum',
		images: [
			'/products/hosp-30s/30-tottle.png',
			'/products/hosp-30s/30-tottle-2.png',
		],
		type: 'hosp-30s',
	},
	{
		id: 16,
		title: '30 Boston',
		closure: '18/415',
		pet: 'PET',
		clear: 'Clear / White',
		mixture: '1500 minimum',
		images: [
			'/products/hosp-30s/30-boston.png',
			'/products/hosp-30s/30-boston-2.png',
		],
		type: 'hosp-30s',
	},
	{
		id: 17,
		title: 'Straight 30ml',
		closure: '18/415',
		pet: 'HDPE',
		clear: 'Natural',
		dimensions: '98 x Ø24',
		mixture: '2000 minimum',
		images: ['/products/hosp-30s/straight-30ml.png'],
		type: 'hosp-30s',
	},
	//hosp-50s
	{
		id: 18,
		title: '50 Tall',
		closure: '18/415',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '108 x Ø30',
		mixture: '1140 minimum',
		images: [
			'/products/hosp-50s/50-tall.png',
			'/products/hosp-50s/50-tall-2.png',
		],
		type: 'hosp-50s',
	},
	{
		id: 19,
		title: '50 Bullet',
		closure: '24/410',
		pet: 'HDPE',
		clear: 'Wht / Nat / Blck',
		dimensions: '79 x Ø35',
		mixture: '1680 minimum',
		images: [
			'/products/hosp-50s/50-bullet.png',
			'/products/hosp-50s/50-bullet-2.png',
			'/products/hosp-50s/50-bullet-3.png',
		],
		type: 'hosp-50s',
	},
	{
		id: 19,
		title: 'Rectangular 50ml',
		closure: '18 / 415 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '80 x Ø41 x Ø22',
		mixture: '2022 minimum',
		images: [
			'/products/hosp-50s/rectangular-50ml.png',
			'/products/hosp-50s/rectangular-50ml-2.png',
		],
		type: 'hosp-50s',
	},
	{
		id: 20,
		title: 'Tottle 50ml',
		closure: 'Oval Flip-Cap',
		pet: 'PP',
		clear: 'Natural',
		dimensions: '81 x Ø50 x Ø30',
		mixture: '1700 minimum',
		images: [
			'/products/hosp-50s/tottle-50ml.png',
			'/products/hosp-50s/tottle-50ml-2.png',
			'/products/hosp-50s/tottle-50ml-pink.png',
			'/products/hosp-50s/tottle-50ml-pink-2.png',
		],
		type: 'hosp-50s',
	},
	//jars-large
	{
		id: 21,
		title: 'Jar 125g',
		closure: '61mm closure',
		pet: 'PP',
		clear: 'White',
		dimensions: '53 x Ø70',
		mixture: '603 minimum',
		images: ['/products/jars-large/jar-125g.png'],
		type: 'jars-large',
	},
	{
		id: 22,
		title: 'Jar 500g',
		closure: '83mm closure',
		pet: 'PP',
		clear: 'White / Natural',
		dimensions: '102 x Ø95',
		mixture: '420 minimum',
		images: [
			'/products/jars-large/jar-500g.png',
			'/products/jars-large/jar-500g-2.png',
		],
		type: 'jars-large',
	},
	{
		id: 23,
		title: 'Jar 1kg',
		closure: '83mm closure',
		pet: 'HDPE',
		clear: 'White',
		dimensions: '183 x Ø92',
		mixture: '224 minimum',
		images: ['/products/jars-large/jar-1kg.png'],
		type: 'jars-large',
	},
	//jars pet
	{
		id: 24,
		title: '175ml Jars',
		closure: '38mm closure - PS seal',
		pet: 'PET',
		clear: 'Clear / Amber / Custom',
		dimensions: '106 x Ø53',
		mixture: '585 minimum',
		images: ['/products/jars-pet/jars-175ml.png'],
		type: 'jars-pet',
	},
	{
		id: 25,
		title: '175ml Jars',
		closure: '38mm closure - PS seal',
		pet: 'PET',
		clear: 'Clear / Amber / Custom',
		dimensions: '106 x Ø53',
		mixture: '585 minimum',
		images: ['/products/jars-pet/jars-175ml-blue.png'],
		type: 'jars-pet',
	},
	// jars small
	{
		id: 26,
		title: 'Jar 10g',
		closure: '-',
		pet: 'Polystyrene (PS)',
		clear: 'Clear',
		dimensions: '19 x Ø35',
		mixture: '1000 minimum',
		images: ['/products/jars-small/jar-10g.png'],
		type: 'jars-small',
	},
	{
		id: 27,
		title: '10ml Cream Jar',
		closure: 'Screw-on lid',
		pet: 'Polystyrene (PS)',
		clear: 'Clear',
		dimensions: '19 x Ø38',
		mixture: '2000 minimum',
		images: ['/products/jars-small/cream-jar-10ml.png'],
		type: 'jars-small',
	},
	{
		id: 28,
		title: '25ml Cream Jar',
		closure: 'Screw-on lid',
		pet: 'Polystyrene (PS)',
		clear: 'Clear',
		dimensions: '33 x Ø38',
		mixture: '1200 minimum',
		images: ['/products/jars-small/cream-jar-25ml.png'],
		type: 'jars-small',
	},
	{
		id: 29,
		title: 'Jar 50g',
		pet: 'PP Inner',
		clear: 'White / Natural',
		dimensions: '51 x Ø59',
		mixture: '621 minimum',
		images: [
			'/products/jars-small/jar-50g.png',
			'/products/jars-small/jar-50g-2.png',
		],
		type: 'jars-small',
	},
	{
		id: 30,
		title: 'Jar 100g',
		closure: '65mm closure',
		pet: 'PP',
		clear: 'Natural',
		dimensions: '36 x Ø71',
		mixture: '528 minimum',
		images: ['/products/jars-small/jar-100g.png'],
		type: 'jars-small',
	},
	//oval
	{
		id: 31,
		title: 'Oval 150ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '128 x Ø53',
		mixture: '572 minimum',
		images: [
			'/products/oval/oval-150ml.png',
			'/products/oval/oval-150ml-2.png',
			'/products/oval/oval-150ml-3.png',
		],
		type: 'oval',
	},
	{
		id: 32,
		title: 'Oval 250ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '150 x Ø60',
		mixture: '415 minimum',
		images: [
			'/products/oval/oval-250ml.png',
			'/products/oval/oval-250ml-2.png',
		],
		type: 'oval',
	},
	{
		id: 33,
		title: 'Oval 300ml',
		closure: '24/410 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '115 x Ø100',
		mixture: '7000 minimum',
		images: [
			'/products/oval/oval-300ml.png',
			'/products/oval/oval-300ml-2.png',
		],
		type: 'oval',
	},
	{
		id: 34,
		title: 'Oval 500ml',
		closure: '24/410 & 28/410 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '144 x Ø110',
		mixture: '7500 minimum',
		images: ['/products/oval/oval-500.png', '/products/oval/oval-500-2.png'],
		type: 'oval',
	},
	//pilfer
	{
		id: 35,
		title: 'Round Pilfer 20ml',
		closure: 'Pilfer /2, /9 Dropper',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '80 x Ø22',
		mixture: '2500 minimum',
		images: ['/products/pilfer/round-pilfer-20ml-red.png'],
		type: 'pilfer',
	},
	{
		id: 36,
		title: 'Round Pilfer 20ml',
		closure: 'Pilfer /2, /9 Dropper',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '80 x Ø22',
		mixture: '2500 minimum',
		images: [
			'/products/pilfer/round-pilfer-20ml.png',
			'/products/pilfer/round-pilfer-20ml-2.png',
		],
		type: 'pilfer',
	},
	{
		id: 37,
		title: 'Round Pilfer 25ml',
		closure: 'Pilfer /3',
		pet: 'PET',
		clear: 'Clear / Amber',
		dimensions: '67 x Ø28',
		mixture: '2500 minimum',
		images: [
			'/products/pilfer/round-pilfer-25ml.png',
			'/products/pilfer/round-pilfer-25ml-2.png',
		],
		type: 'pilfer',
	},
	{
		id: 38,
		title: 'Round Pilfer 100ml',
		closure: 'Pilfer /3',
		pet: 'PET',
		clear: 'Clear / Amber',
		dimensions: '108 x Ø42',
		mixture: '935 minimum',
		images: [
			'/products/pilfer/round-pilfer-100ml.png',
			'/products/pilfer/round-pilfer-100ml-2.png',
		],
		type: 'pilfer',
	},
	//pumps
	{
		id: 39,
		title: 'Spray Pumps',
		closure: 'Various sizes',
		clear: 'Various colors',
		mixture: '500/400 minimum',
		images: [
			'/products/pumps/spray-pumps.png',
			'/products/pumps/spray-pumps-2.png',
		],
		type: 'pumps',
	},
	{
		id: 40,
		title: 'Triggers',
		closure: '28/410',
		clear: 'Natural',
		mixture: '400 minimum',
		images: ['/products/pumps/triggers.png'],
		type: 'pumps',
	},
	{
		id: 41,
		title: 'Lotion Pumps',
		closure: '24/410 / 28/410',
		clear: 'Natural/Black/White',
		mixture: '500/400 minimum',
		images: ['/products/pumps/lotion-pumps.png'],
		type: 'pumps',
	},
	{
		id: 42,
		title: 'Flips',
		closure: '24/410 / 28/410',
		pet: 'PP',
		clear: 'Various colors',
		mixture: '420/400 minimum',
		images: ['/products/pumps/flips.png', '/products/pumps/flips-2.png'],
		type: 'pumps',
	},
	{
		id: 43,
		title: 'Smooth',
		closure: '24/410',
		pet: 'PP',
		clear: 'Natural/Black/White',
		mixture: '420 minimum',
		images: ['/products/pumps/smooth.png'],
		type: 'pumps',
	},
	{
		id: 44,
		title: 'Tall',
		closure: '24/410',
		pet: 'PP',
		clear: 'Natural/White',
		mixture: '420 minimum',
		images: ['/products/pumps/tall.png'],
		type: 'pumps',
	},
	{
		id: 45,
		title: "Ridge 30's",
		closure: '38',
		pet: 'HDPE',
		clear: 'White/Black/Natural',
		mixture: '585 minimum',
		images: ['/products/pumps/ridge-30s.png'],
		type: 'pumps',
	},
	//rectangular
	{
		id: 46,
		title: 'Rectangular 50ml',
		closure: '18/415 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '80 x Ø41 x Ø22',
		mixture: '2022 minimum',
		images: [
			'/products/pumps/Rectangular-50ml.png',
			'/products/pumps/Rectangular-50ml-2.png',
		],
		type: 'rectangular',
	},
	{
		id: 47,
		title: 'Rectangular 200ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '129 x Ø59 x Ø35',
		mixture: '560 minimum',
		images: [
			'/products/Rectangular/Rectangular-200ml.png',
			'/products/Rectangular/Rectangular-200ml-2.png',
		],
		type: 'rectangular',
	},
	{
		id: 48,
		title: 'Rectangular 300ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '131 x Ø69 x Ø42',
		mixture: '408 minimum',
		images: [
			'/products/pumps/Rectangular-300ml.png',
			'/products/pumps/Rectangular-300ml-2.png',
		],
		type: 'rectangular',
	},
	{
		id: 49,
		title: 'Rectangular 500ml',
		closure: '24/410 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '138 x Ø88 x Ø58',
		mixture: '7500 minimum',
		images: [
			'/products/pumps/Rectangular-500ml.png',
			'/products/pumps/Rectangular-500ml-2.png',
		],
		type: 'rectangular',
	},
	//securi-tainers
	{
		id: 50,
		title: 'Tablet Container 62 x 152',
		clear: 'White',
		dimensions: 'Ø62 x 152',
		mixture: '1000 minimum',
		images: [
			'/products/securi-tainers/tablet-container-62-152.png',
			'/products/securi-tainers/tablet-container-62-152-2.png',
		],
		type: 'securi-tainers',
	},
	{
		id: 51,
		title: 'Tablet Container 35 x 82',
		clear: 'White',
		dimensions: 'Ø35 x 82',
		mixture: '900 minimum',
		images: [
			'/products/securi-tainers/tablet-container-35-82.png',
			'/products/securi-tainers/tablet-container-35-82-2.png',
		],
		type: 'securi-tainers',
	},
	{
		id: 52,
		title: 'Tablet Container 35 x 63',
		clear: 'White',
		dimensions: 'Ø35 x 63',
		mixture: '1000 minimum',
		images: [
			'/products/securi-tainers/tablet-container-35-63.png',
			'/products/securi-tainers/tablet-container-35-63-2.png',
		],
		type: 'securi-tainers',
	},
	{
		id: 53,
		title: 'Tablet Container 35 x 52',
		clear: 'White',
		dimensions: 'Ø35 x 52',
		mixture: '1300 minimum',
		images: [
			'/products/securi-tainers/tablet-container-35-52.png',
			'/products/securi-tainers/tablet-container-35-52-2.png',
		],
		type: 'securi-tainers',
	},
	{
		id: 54,
		title: 'Tablet Container 62 x 90',
		clear: 'White',
		dimensions: 'Ø62 x 90',
		mixture: '1300 minimum',
		images: [
			'/products/securi-tainers/tablet-container-62-90.png',
			'/products/securi-tainers/tablet-container-62-90-2.png',
		],
		type: 'securi-tainers',
	},
	//soft-squeeze
	{
		id: 55,
		title: 'Soft 250ml',
		closure: '24/410 closure',
		pet: 'LDPE',
		clear: 'Natural',
		dimensions: '175 x Ø50',
		mixture: '420 minimum',
		images: [
			'/products/soft-squeeze/soft-squeeze-250ml.png',
			'/products/soft-squeeze/soft-squeeze-250ml-2.png',
			'/products/soft-squeeze/soft-squeeze-250ml-3.png',
		],
		type: 'soft-squeeze',
	},
	{
		id: 56,
		title: 'Soft 100ml',
		closure: '24/410 closure',
		pet: 'LDPE',
		clear: 'Natural',
		dimensions: '117 x Ø40',
		mixture: '840 minimum',
		images: [
			'/products/soft-squeeze/soft-squeeze-100ml.png',
			'/products/soft-squeeze/soft-squeeze-100ml-2.png',
		],
		type: 'soft-squeeze',
	},
	//square
	{
		id: 57,
		title: 'Square 50ml',
		closure: '18/415 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '74 x Ø32 x Ø32',
		mixture: '2093 minimum',
		images: [
			'/products/square/square-50ml.png',
			'/products/square/square-50ml-2.png',
		],
		type: 'square',
	},
	{
		id: 58,
		title: 'Square 100ml',
		closure: '24/410 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '98 x Ø38 x Ø35',
		mixture: '980 minimum',
		images: [
			'/products/square/square-100ml.png',
			'/products/square/square-100ml-2.png',
		],
		type: 'square',
	},
	{
		id: 59,
		title: 'Square 200ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '128 x Ø46 x Ø46',
		mixture: '540 minimum',
		images: [
			'/products/square/square-200ml.png',
			'/products/square/square-200ml-2.png',
		],
		type: 'square',
	},
	{
		id: 56,
		title: 'Square 300ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '140 x Ø53 x Ø53',
		mixture: '351 minimum',
		images: ['/products/square/square-300ml.png'],
		type: 'square',
	},
	{
		id: 57,
		title: 'Square 500ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '177 x Ø60 x Ø60',
		mixture: '490 minimum',
		images: [
			'/products/square/square-500ml.png',
			'/products/square/square-500ml-2.png',
		],
		type: 'square',
	},
	//straight
	{
		id: 58,
		title: 'Straight 30ml',
		closure: '18/415 closure',
		pet: 'HDPE',
		clear: 'Natural',
		dimensions: '98 x Ø24',
		mixture: '2000 minimum',
		images: ['/products/straight/straight-30ml.png'],
		type: 'straight',
	},
	{
		id: 59,
		title: 'Straight 50ml',
		closure: '18/415 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '93 x Ø30',
		mixture: '1976 minimum',
		images: [
			'/products/straight/straight-50ml.png',
			'/products/straight/straight-50ml-2.png',
		],
		type: 'straight',
	},
	{
		id: 60,
		title: 'Straight 250ml',
		closure: '24/410 closure',
		pet: 'HDPE',
		clear: 'White/Natural',
		dimensions: '165 x Ø50',
		mixture: '420 minimum',
		images: [
			'/products/straight/straight-250ml.png',
			'/products/straight/straight-250ml-2.png',
		],
		type: 'straight',
	},
	{
		id: 61,
		title: 'Straight 250ml PET',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '161 x Ø50',
		mixture: '420 minimum',
		images: ['/products/straight/straight-250ml-pet.png'],
		type: 'straight',
	},
	{
		id: 62,
		title: 'Straight 500ml PET',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '187 x Ø64',
		mixture: '408 minimum',
		images: [
			'/products/straight/straight-500ml-pet.png',
			'/products/straight/straight-500ml-pet-2.png',
		],
		type: 'straight',
	},
	//tall
	{
		id: 63,
		title: 'Tall 250ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '175 x Ø48',
		mixture: '435 minimum',
		images: [
			'/products/tall/tall-250ml-150ml.png',
			'/products/tall/tall-250ml-150ml-2.png',
		],
		type: 'tall',
	},
	{
		id: 64,
		title: 'Tall 100ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '129 x Ø36',
		mixture: '1016 minimum',
		images: ['/products/tall/tall-100ml.png'],
		type: 'tall',
	},
	{
		id: 65,
		title: 'Tall 50ml',
		closure: '18/415 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '102 x Ø30',
		mixture: '1880 minimum',
		images: ['/products/tall/tall-50ml.png', '/products/tall/tall-50ml-2.png'],
		type: 'tall',
	},
	//taper
	{
		id: 66,
		title: 'Taper 300ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '138 x Ø63 x Ø55',
		mixture: '288 minimum',
		images: [
			'/products/taper/taper-300ml.png',
			'/products/taper/taper-300ml-2.png',
		],
		type: 'taper',
	},
	//tottle
	{
		id: 67,
		title: 'Tottle 30ml',
		closure: 'Tottle cap',
		pet: 'PP',
		clear: 'Natural',
		dimensions: '73 x Ø36 x Ø24',
		mixture: '2600 minimum',
		images: ['/products/tottle/tottle-30ml.png'],
		type: 'tottle',
	},
	{
		id: 68,
		title: 'Tottle 50ml',
		closure: 'Oval Flip-Cap',
		pet: 'PP',
		clear: 'Natural',
		dimensions: '81 x Ø50 x Ø30',
		mixture: '1700 minimum',
		images: [
			'/products/tottle/tottle-50ml.png',
			'/products/tottle/tottle-50ml-2.png',
			'/products/tottle/tottle-50ml-3.png',
			'/products/tottle/tottle-50ml-4.png',
		],
		type: 'tottle',
	},
	{
		id: 69,
		title: 'Tottle 250ml',
		closure: 'Oval Flip-Cap',
		pet: 'HDPE',
		clear: 'Natural',
		dimensions: '179 x Ø66 x Ø42',
		mixture: '20,000 minimum',
		images: [
			'/products/tottle/tottle-250.png',
			'/products/tottle/tottle-250-2.png',
		],
		type: 'tottle',
	},
];

export const bestSellers = [
	{
		id: 63,
		title: 'Tall 250ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '175 x Ø48',
		mixture: '435 minimum',
		images: [
			'/products/tall/tall-250ml-150ml.png',
			'/products/tall/tall-250ml-150ml-2.png',
		],
		type: 'tall',
	},
	{
		id: 55,
		title: 'Soft 250ml',
		closure: '24/410 closure',
		pet: 'LDPE',
		clear: 'Natural',
		dimensions: '175 x Ø50',
		mixture: '420 minimum',
		images: [
			'/products/soft-squeeze/soft-squeeze-250ml.png',
			'/products/soft-squeeze/soft-squeeze-250ml-2.png',
			'/products/soft-squeeze/soft-squeeze-250ml-3.png',
		],
		type: 'soft-squeeze',
	},
	{
		id: 33,
		title: 'Oval 300ml',
		closure: '24/410 closure',
		pet: 'PVC',
		clear: 'Clear',
		dimensions: '115 x Ø100',
		mixture: '7000 minimum',
		images: [
			'/products/oval/oval-300ml.png',
			'/products/oval/oval-300ml-2.png',
		],
		type: 'oval',
	},
	{
		id: 48,
		title: 'Rectangular 300ml',
		closure: '24/410 closure',
		pet: 'PET',
		clear: 'Clear',
		dimensions: '131 x Ø69 x Ø42',
		mixture: '408 minimum',
		images: [
			'/products/Rectangular/Rectangular-300ml.png',
			'/products/Rectangular/Rectangular-300ml-2.png',
		],
		type: 'rectangular',
	},
];

export const mightLike = [
	products[21],
	products[38],
	products[66],
	products[25],
];
