import { Metadata } from 'next';
import React from 'react';
import TopSellers from './TopSellers';

export const metadata: Metadata = {
	title: 'Purple Line Plastics | Top sellers',
	description: 'Generated by create next app',
};

export default function page() {
	return (
		<main>
			<TopSellers />
		</main>
	);
}
